
project_id = "mgxjqujcsajvogaoqccz"

[api]
enabled = true
port = 54321
schemas = ["public", "storage"]

[db]
port = 54322

[studio]
enabled = true
port = 54323
api_url = "http://localhost"

# Define the businesses table with social media fields
[[db.remote.tables]]
name = "businesses" 
columns = [
  { name = "id", type = "uuid" },
  { name = "name", type = "text" },
  { name = "description", type = "text", nullable = true },
  { name = "category", type = "text", nullable = true },
  { name = "subcategory", type = "text", nullable = true },
  { name = "location", type = "text", nullable = true },
  { name = "province", type = "text", nullable = true },
  { name = "city", type = "text", nullable = true },
  { name = "contact_person", type = "text", nullable = true },
  { name = "phone", type = "text", nullable = true },
  { name = "email", type = "text", nullable = true },
  { name = "department", type = "text", nullable = true },
  { name = "logo", type = "text", nullable = true },
  { name = "images", type = "text[]", nullable = true },
  { name = "user_id", type = "uuid" },
  { name = "facebook", type = "text", nullable = true },
  { name = "instagram", type = "text", nullable = true },
  { name = "whatsapp", type = "text", nullable = true },
  { name = "website", type = "text", nullable = true },
  { name = "created_at", type = "timestamp with time zone" },
  { name = "updated_at", type = "timestamp with time zone" }
]
