// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mgxjqujcsajvogaoqccz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1neGpxdWpjc2Fqdm9nYW9xY2N6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxNDkxNjksImV4cCI6MjA1OTcyNTE2OX0.MLpNTe3pTXHdvd00ygdu_zgDYh9_a_O_sgorudazQBU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);